version: "3.7"
services:
  app:
    build:
      args:
        user: football
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: football
    container_name: football-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - football

  db:
    image: mysql:8.0
    container_name: football-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - football

  redis:
      image: redis:alpine
      container_name: football-redis
      restart: unless-stopped
      ports:
          - 6379:6379
      networks:
          - football

  nginx:
    image: nginx:alpine
    container_name: football-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - football

networks:
  football:
    driver: bridge
